secretGenerator:
- name: mysql-pass
  literals:
  - password=password
configMapGenerator:
- name: telegraf-config
  files:
    - grafana/telegraf.conf
resources:
  - nginx.yml
  - mysql.yml
  - phpmyadmin.yml
  - wordpress.yml
  - grafana.yml
  - influxdb.yml
  - telegraf.yml
  - ingress.yml
  - ftps.yml
