apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: ft_services
  name: nginx
  namespace: default
  resourceVersion: "19429"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginx
  uid: d11dffe3-6cc8-4318-8808-0253f4993f38
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: mynginx
        imagePullPolicy: Never
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nginx
    name: nginx
    namespace: default
    resourceVersion: "21092"
    selfLink: /api/v1/namespaces/default/services/nginx
    uid: efb06b5a-4275-46b3-bed7-bd7b30713895
  spec:
    clusterIP: 10.96.9.106
    externalTrafficPolicy: Cluster
    ports:
    - name: 80-80
      nodePort: 32744
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
