apiVersion: apps/v1
kind: Deployement
metadata:
  name: telegraf
  labels:
      app: telegraf
spec:
  template:
    metadata:
      labels:
        app: telegraf
  containers:
    - name: telegraf
      image: telegraf:alpine
      imagePullPolicy: Always
  # volumes:
  #   - name: telegraf-config
  #     configMap:
  #       name: telegraf-config